### ISSUE TITLE
Crash right after starting the app

### ISSUE THREAD

**Issue by stuermera** [Kirezar/VitaGrafixConfigurator#1]
The app starts right after I started it.

Error C2-12828-1
Save core file succeeded.
ux0:data/psp2core-1535662443-0x0000162e91-eboot.bin.psp2dmp

PS Vita, 3.68 H-encore, SD2Vita.

**Comment by Kirezar** [comment]
Is the directory ux0:/data/VitaGrafix being created? as well as the config file in that directory?

**Comment by stuermera** [comment]
Yes it is. Also vitagrafix and kuio files in ur0:tai/
I used vitagrafix with config file the last days, playing Killzone and Ridge Racer with it.
So it is working so far.

**Comment by Kirezar** [comment]
ok, can you send me your psp2core-1535662443-0x0000162e91-eboot.bin.psp2dmp file?

**Comment by stuermera** [comment]
Hi!
Seems the filename changes everytime... attached the dmp file from now.

[psp2core-1535740604-0x0000bb2625-eboot.bin.psp2dmp.zip](https://github.com/Kirezar/VitaGrafixConfigurator/files/2341173/psp2core-1535740604-0x0000bb2625-eboot.bin.psp2dmp.zip)

**Comment by Kirezar** [comment]
Damn man, you seem to be the only one with that problem and I can't replicate it, I'm gonna look at the dump see if I can find where something is wrong, meanwhile try re-installing it if you didn't yet, backup your config file for VitaGrafix and rename it something else

**Comment by stuermera** [comment]
Uh I think I have found the issue... 🤦🏻‍♂️

I configured my config.txt with comments so I don't have to rely on the PCSB gamecodes. I wrote "#gamename" (for example #Killzone) the line before each "[PCSBxxxxx]".

I have now completely deleted everything except the suprx and kuio files. Your app is working now for me 👍

Perhaps only showing the installed supported games instead of all supported games would make it more convenient...

Great work! 😉

**Comment by Kirezar** [comment]
Ahh nice nice, and did VitaGrafix work fine with those comments? I was actually thinking about doing what you did as well, but I was unsure if VitaGrafix would react badly to it. I guess I'll look into that as well as adding an "Installed Games" tab or option or something of the kind!

**Comment by stuermera** [comment]
Yes it was working fine 👍🏻

By the way, I think the default resolution of WRC 3 and 4 is 720x408 and not 960x544 as shown in your app...

**Comment by Kirezar** [comment]
The default is not the game default, but the plugin default, I think I should make it more clear :P

**Comment by neo305** [comment]
same just happened to me after updating to 8.0. I went back to 7.21 and it boots fine again.
