### ISSUE TITLE
An error occurred while reading config file

### ISSUE THREAD

**Issue by petecolon1985** [Kirezar/VitaGrafixConfigurator#14]
I keep getting that error when changing resolution in games. I tried a couple games and it does this with all of them. But when I leave it as default it loads fine and no problem. Also on the bottom there is an error that says failed to parse config (line 50, POS 6): invalid token

**Comment by Kirezar** [comment]
Show me your config.txt file and your patchlist.txt file please.

**Comment by petecolon1985** [comment]
Hey I figured it out. U won't beleive how stupid I was. When I was entering the screen resolution I was using a × symbol instead of a x. So I went back and entered it correctly and now everything is working fine. What a idiot 🤦🏾‍♂️🤦🏾‍♂️

**Comment by Kirezar** [comment]
Glad you did, I should add that as an option though, I've had people request it before, since it's on the same screen, as it would be more practical.

**Comment by petecolon1985** [comment]
Yea that would be pretty cool. Or maybe u can just have preset resolutions set, so like you can just just the dpad and select left or right for different resolutions. But either way the mod is awesome and it works great I really appreciate developers like you putting all your free time in to make the vita an awesome experience you guys are awesome.
