### ISSUE TITLE
Vitagrafix erorr

### ISSUE THREAD

**Issue by auza104** [Kirezar/VitaGrafixConfigurator#17]
![IMG_20200330_024908](https://user-images.githubusercontent.com/61713842/77865940-1df85780-7231-11ea-9556-4d00b95d7862.jpg)

How can i fix this problem?

**Comment by Kirezar** [comment]
Can you post your config file please?

**Comment by auza104** [comment]
[config.txt](https://github.com/Kirezar/VitaGrafixConfigurator/files/4401949/config.txt)
[patchlist.txt](https://github.com/Kirezar/VitaGrafixConfigurator/files/4401950/patchlist.txt)

**Comment by Kirezar** [comment]
Did you just mess with the settings for Need For Speed MW in the configurator, or did you change stuff by hand? I'm seeing some MSAA=0x in the config file, and that shouldn't be possible through the app.

In any case, delete your config.txt and see if the newly generated one works

**Comment by auza104** [comment]
I deleted the file when open the game give me erorr and the game version is not supported then i check the version found it 1.0.0
How can i download 1.0.1 version 
I looked for it in many sites and not find
