### ISSUE TITLE
The app makes Vita bootloop

### ISSUE THREAD

**Issue by bololabich** [Kirezar/VitaGrafixConfigurator#2]
I've installed latest VitaGrafix plugin (and it does work properly, showing info when starting a game with some changes applied) and after installing VitaGrafixConfigurator with gamelist.txt put into the right folder, as soon as I open up the app it makes a config.txt file, and when I close the app and try to start any other app, vita just freezes and then when rebooted it stays on the henkaku logo, right after the plugins are loaded (as I have LED disabling plugin and the LEDs go black).

**Comment by Kirezar** [comment]
Can you post your ur0:/tai/config.txt file and your ux0:/VitaGrafix/config.txt file?

**Comment by bololabich** [comment]
Thanks for interest.
[VitaGrafix_config.txt](https://github.com/Kirezar/VitaGrafixConfigurator/files/2497014/VitaGrafix_config.txt)
[tai_config.txt](https://github.com/Kirezar/VitaGrafixConfigurator/files/2497033/tai_config.txt)

**Comment by Kirezar** [comment]
What happens if you just run VitaGrafix without the app, and just create the config.txt yourself and add one compatible game in there manually? Does it crash as well?

**Comment by bololabich** [comment]
Hymm, that's surprising, it crashes as well with just that:
[MAIN]
ENABLED=1
[PCSD00071]
IB=960x544
So it's probably the plugin's issue it appears

**Comment by Kirezar** [comment]
Mmm ok, I checked your config and everything seems to be okay, maybe you have some conflicting plugins? try disabling kuio and vsh, make sure you have all the files in the right folder, and retry, maybe you have something missing somewhere that you haven't noticed yet

**Comment by bololabich** [comment]
I'll try disabling other pluggins (except these that are required I mean) and report back when have some time.
