### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by mbragante** [Kirezar/VitaGrafixConfigurator#3]
Hi developer. I'm having certain issues with my Vitagrafix configurator that even when I upgrade it to the latest version, I still get the message of version outdated, and even uninstalling and reinstalling vpk and deleting local vitagrafix configurator data.
Any tips to solve this?

**Comment by Kirezar** [comment]
Ok, can you get me a screenshot of the version warning? + your versions.txt file?

**Comment by Kirezar** [comment]
Ok I guess the bug I thought was fixed really wasn't. Anyway, just go to your data and make sure the versions.txt there are 1.3 and not 1.32. I thought I had fixed that and apparently not. Still an easy fix
ux0:/data/VitaGrafix/versions.txt and change 1.32 to 1.3

**Comment by mbragante** [comment]
Okay, It worked now, thank you so much :)
