### ISSUE TITLE
Vitagrafix 4.0 alpha broke configurator

### ISSUE THREAD

**Issue by Shinriji** [Kirezar/VitaGrafixConfigurator#5]
I updated VG 3.2 to 4.0 alpha today and the configurator crashes. I deleted the app and reinstalled it and it works until I try to update the game list, so the bug is probably related to that (I marked to auto update game list).

Thanks for your work!

**Comment by EnekoT2001** [comment]
I have the alpha working with VG configurator, I just didn't use the official patchlist and renamed it to gamelist.txt bc vitagrafix configurator doesn't know how to handle it (for now), did you do this?

**Comment by Kirezar** [comment]
Just want to let you know that I've started working on it =) having some bugs right now because I'm not using the gamelist.txt anymore, and I'm using the patchlist.txt directly from VitaGrafix, but my reading code is still far from perfect :P

**Comment by Kirezar** [comment]
Guys, it has been released, thank you all for your patience! Please help me test and see if there's any bugs with it

**Comment by Shinriji** [comment]
Downloaded and everything is working as expected. I already pushed a request to make the patchlist.txt in alphabetical order, so make everything just like before. 

Thanks again for your work.
