### ISSUE TITLE
Can't run vitagrafix's new update

### ISSUE THREAD

**Issue by Marioh2451** [Kirezar/VitaGrafixConfigurator#8]
It says
An error occured:
[string "?"]:799 attempt yo Index a nil valiente
Press X to restart.
Press O to enable/disable FTP.

If you press X or O It doesn't do notjing lol. Help me please

**Comment by Kirezar** [comment]
Someone on reddit had the same problem this was their solution, try it. 

"nvm,but in versions.txt it said app 1.3 so i deleted the the folder and unistalled the plugin,downloaded and installed manually and it works know.Thanks for help anyway and for this awesome configurator."

**Comment by Marioh2451** [comment]
Where is that version.txt and the gamelist.txt at?

**Comment by Kirezar** [comment]
They shouldn't matter anymore, but they were at ux0:/data/VitaGrafix

The bug is that it's not being able to create the game list in code, and when it tries to access it it access an inexistent object. But just deleting your VitaGrafix folder, and installing the app again should fix it.

**Comment by Marioh2451** [comment]
Fixed, thank you very much!
